name: smp-sea-ice
channels: 
  - defaults
dependencies:
  - geopandas
  - python=3.7.3
  - jupyter
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.25.0
  - ipython=7.7.0
  - pyproj
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - statsmodels=0.10.1
  - pip
  - pip:
      - snowmicropyn==1.0.1
      - geostatsmodels==0.3.3
