# adapted from post by Hamel Husain: https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2
name: binder
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout files in repo
      uses: actions/checkout@master
      
    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MYBINDERORG_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
        IMAGE_NAME: "kingjml/smp-sea-ice"
