# adapted from post by Hamel Husain: https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2
name: binder
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Create-MyBinderOrg-Image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout files in repo
      uses: actions/checkout@master
    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MYBINDERORG_CACHE: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
        IMAGE_NAME: "kingjml/smp-sea-ice" # if we don't set this, the image will probably have m9brady as the creator
