# adapted from post by user Sylvaticus: https://discourse.jupyter.org/t/how-to-build-mybinder-image-automatically-at-each-commit/5381/3
# this workflow will hopefully cache the binder image after a push/PR to master so the badge-button doesn't have to be clicked in order to trigger a rebuild
name: binder
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Create-MyBinderOrg-Image:
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
        IMAGE_NAME: kingjml/smp-sea-ice # note that lowercase is required
